version: '3'
services:
  node-app:
    build:
      context: ./API
    ports:
      - 3000:3000
    networks:
      - my-network
  react-app:
    build:
      context: ./FE
    ports:
      - 80:80
    networks:
      - my-network

networks:
  my-network:
    driver: bridge